version: 2.1

commands:
  install_git_secret:
    description: Install git secret cli
    steps:
      - run: sudo apt-get update && sudo apt-get install apt-transport-https
      - run: echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
      - run: wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install git-secret

  import_gpg_key:
    description: Import gpg key from env var
    parameters:
      variable_name:
        type: env_var_name
        default: GPG_KEY # TODO: pass through job
        description: environment variable containing gpg key
    steps:
      - run: echo -e "$<< parameters.variable_name >>" | gpg --import --no-tty --batch --yes

  reveal_secrets:
    description: Reveal the secrets
    steps:
      - run: 
          command: |
            ls
            git secret reveal -f 
      #(cd ~/project && git secret reveal -f)

# executors:
#   default:
#     description: Job config
#     docker:
#       - image: circleci/node:10.16.3

jobs:
  build_and_test:
    working_directory: ~/project
    docker:
        - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - attach_workspace:
          at: ./
      - install_git_secret
      - import_gpg_key
      - reveal_secrets
      - persist_to_workspace:
          root: ./
          paths:
            - ./
      - run:
          name: Run Tests
          command: pytest -vv tests

workflows:
  version: 2.1
  test-all:
    jobs:
      - build_and_test