version: 2.1

jobs:
  build_and_test:
    working_directory: ~/project
    docker:
        - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest -vv tests

workflows:
  version: 2.1
  test-all:
    jobs:
      - build_and_test