version: 2.1
jobs:
    test_project:
      working_directory: ~/project
      docker:
          - image: circleci/python:3.7.2
      steps:
        - checkout
        - run:
            name: Running Tests
            command: |
              virtualenv venv
              . venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              pytest -vv tests
orbs:
  git-secret: lyvly/git-secret@0.1.0
workflows:
  version: 2.1
  build:
    jobs:
      - git-secret/install_and_decrypt
  test-all:
    jobs:
      - test_project