version: 2.1

jobs:
  build_and_test:
    working_directory: ~/project
    docker:
        - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            ls
            sudo apt-get install bsdmainutils
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Unencrypt files
            git clone https://github.com/elasticdog/transcrypt.git
            cd transcrypt
            sudo ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt
            cd ..
            transcrypt -c $TRANSCRYPT_CYPHER -p $TRANSCRYPT_PASSWORD -y -F
            # Override defaults
            export BFEX_CERTS_DIR = certs
            export PROJECT_DIR = .
            pytest -vv tests
workflows:
  version: 2.1
  test-all:
    jobs:
      - build_and_test:
          context: bfex_project